### ISSUE TITLE
Fix StyleCop Warnings

### ISSUE THREAD

**Issue by OkGoDoIt** [okta/okta-auth-dotnet#20]
There's a lot of StyleCop warnings that need to be fixed, mostly related to documenting internal members.  Additionally there are some capitalization issues in some comments.

**Comment by gitvinit** [comment]
Is anyone working on this if not I can take a look at fixing these issues?

**Comment by laura-rodriguez** [comment]
Hi @gitvinit ,
This is not in our backlog right now. Feel free to take a look :).

Thanks!

**Comment by laura-rodriguez** [comment]
Fixed in #36
