### ISSUE TITLE
Setup proxy for Okta SDK

### ISSUE THREAD

**Issue by jllanes1987** [okta/okta-auth-dotnet#26]
Hi!
I'm trying to use the SDK in order to call Okta endpoints. I’m using the Official .NET SDK for the Okta API version 1.4.1.

When I'm executing:

await client.Users.GetUserAsync(username);

the call stays on Pending status forever. We work behind a proxy, and I think that is the problem, because when we change the configuration in Postman, we get the same result (Pending).

I found this:
https://github.com/okta/okta-auth-dotnet/blob/master/Okta.Sdk.Abstractions/Configuration/OktaClientConfiguration.cs

And following this instruction:

//Gets or sets the optional proxy to use for HTTP connections. If <c>null</c>, the default system //proxy is used, if any.

I set up the proxy like this:

     var client = new OktaClient(new OktaClientConfiguration
                {
                    ConnectionTimeout = connectionTimeout,
                    OktaDomain = WebConfigurationManager.AppSettings["okta:OktaDomain"],
                    Token = WebConfigurationManager.AppSettings["okta:APIToken"],
                    Proxy = null,
                });

But still not working.
We don’t have a yaml config file, we have the configuration explicitly passed to the constructor.

Please, can you help me with this matter?

Regards,
Jormary.

**Comment by laura-rodriguez** [comment]
Hi @jllanes1987 ,

Do you have any specific details of your proxy you can share with us, so we can try to reproduce it?

**Comment by jllanes1987** [comment]
Hi @laura-rodriguez ,
Sorry, nothing specific about our proxy. Basically we need Okta to use the system's default proxy configurations.

**Comment by laura-rodriguez** [comment]
Ok, then give me a few days to see if we can prioritize this, and spend some time trying to reproduce the issue.

**Comment by laura-rodriguez** [comment]
@jllanes1987, since this is also "failing" in postman, can you please provide a postman example of (1) making the call with proxy settings that work (if any) and (2) making a call without proxy settings where the call fails? Does it work as expected without a proxy?

**Comment by jllanes1987** [comment]
Hi @laura-rodriguez,

Postman test:
I'm testing with the Okta user API, specifically with Find User, Get User and Get Current User endpoints.
(1) With the option to allow Postman to use the system's default proxy configurations, all the endpoints calls works.
(2) Without this option enable all the endpoints calls fails.

![PostmanErrorProxy](https://user-images.githubusercontent.com/20603278/70625484-74914580-1bf0-11ea-9138-04c686beadba.png)

Does Okta provide a similar option to allow to use the system's default proxy configurations?

**Comment by jllanes1987** [comment]
Hi @laura-rodriguez,
I think we got it.
We followed this instruction:
https://github.com/okta/okta-auth-dotnet#configuration-reference

And we created an okta.yaml file in a .okta folder in the project's root directory with the proxy information. This is only working for us if we keep the client constructor with the domain and token data.

So, it is working now!
Thanks :)

**Comment by laura-rodriguez** [comment]
I'm glad you got it working! Just to clarify, if you don't use a .okta folder, and you pass those params inline when you create a new Okta client, does it still work? Also, what happens if you put your token and domain in the same .yaml file inside your .okta folder? Aren't those grabbed by the constructor?
