### ISSUE TITLE
.NET Core - HttpClient

### ISSUE THREAD

**Issue by gituser22kk** [okta/okta-auth-dotnet#27]
We use .NET Core 2.2 and pass a httpClient when creating the AuthenticationClient()... since we want to forward user's browser info and IP address.

1. How do we set the user agent in the httpClient's headers. Looks like the SDK overwrites it. We want to forward web-client's browser's info.

2. How do we re-use the httpClient in our next call to AuthenticationClient()? It gives an error "This instance has already started one or more requests. Properties can only be modified before sending the first request.". Looks like #1 above is again trying to set the headers. Does it expect a fresh httpClient for each call to AuthenticationClient()?

Thank you!

**Comment by laura-rodriguez** [comment]
Hi @gituser22kk ,

Thanks for your question.

Give me some time to take a look at this and I'll get back to you.

**Comment by chrismorris-okta** [comment]
Hi @gituser22kk, 

If you don't can you share a bit more details with us so we can help?

Can you tell us why you would like to forward the client browser info? Is there a specific flow or use case you are trying to accomplish? For example, are you trying to use this info in an adaptive MFA policy? https://www.okta.com/sites/default/files/okta_mfa-datasheet.pdf

**Comment by gituser22kk** [comment]
We use SDK to authenticate the user... the user's aren't logging directly to Okta's portal or using any of the sign-in widget.

Thus, we need to forward the browser info for many reasons:
MFA policies.
User's IP address restrictions (black list etc.)
Record in Okta's log with the correct info... and any reporting from that.

**Comment by chrismorris-okta** [comment]
Got it. Thanks for those details. #1 isn't possible at the moment but I've created a ticket for our team to add this in a future release of the SDK. We hope to support this capability in the very near future.

**Comment by laura-rodriguez** [comment]
Hi @gituser22kk ,

We have fixed the user-agent issue as part of #28.

We also added a section about sending additional info in the headers in the [readme](https://github.com/okta/okta-auth-dotnet#send-information-via-requests-headers).
