### ISSUE TITLE
Issue with ActivateFactorOptions method of Okta.Auth.Sdk , getting error code E0000022

### ISSUE THREAD

**Issue by amitSahu9** [okta/okta-auth-dotnet#37]
Facing an issue while performing an activation request for SMS factor. ActivateFactorOptions() is throwing the error as "The endpoint does not support the provided HTTP method" with an error code of E0000022.
Here goes the code :- 

           var activateFactorOptions = new ActivateFactorOptions()
            {
                FactorId = this.Id,
                PassCode = passCode,
                StateToken = this.stateController.StateToken,
            };

            var authResponse = await this.authnClient.ActivateFactorAsync(activateFactorOptions);
            this.stateController.ProcessAuthnResponse(authResponse);

I tried hitting custom endpoint using the PostAsync() method in the Okta.Auth.Sdk , but it throws a different error, it says "StateToken is required in this context" ,  even if i am passing the state token along with the payload. 
here it is :-  
                 var activateFactorOptions = new ActivateFactorOptions()
            {
                FactorId = this.Id,
                StateToken = this.stateController.StateToken,
                PassCode = passCode,
            };

            var request = new HttpRequest()
            {
                Uri = "/api/v1/authn/factors/mblry4uxieTrPiOcp0h7/lifecycle/activate",
                Payload = activateFactorOptions,
            };

            var authResponse = await this.authnClient.PostAsync<AuthenticationResponse>(request);
Need help regarding this..!

## Current behavior

Throwing error related to endpoint
## Expected behavior

The expected behaviour should be , it should activate the sms factor without throwing any error and should return the response as well.

## Environment

- OS: windows 10
- Browser: 

- .Net Framework: 4.8

- Other:

**Comment by bryanapellanes-okta** [comment]
Hi @amitSahu9 ,
Thank you for reaching out to report this, and I'm sorry you're seeing that error.  I will review this further internally to gain understanding as to the root of the issue.  

In the mean time are you able to submit the request using Postman with the same result?  I'd like to better understand whether the cause is rooted in the Sdk or if it is potentially a problem deeper in the system.

I look forward to hearing back!

**Comment by amitSahu9** [comment]
> Hi @amitSahu9 ,
> Thank you for reaching out to report this, and I'm sorry you're seeing that error. I will review this further internally to gain understanding as to the root of the issue.
> 
> In the mean time are you able to submit the request using Postman with the same result? I'd like to better understand whether the cause is rooted in the Sdk or if it is potentially a problem deeper in the system.
> 
> I look forward to hearing back!

Hey @bryanapellanes-okta  , 
Thank you for your quick response on this issue .
As you asked ,  I have tried submitting that same request using postman and its working fine over there , i even tried to create a custom client without using the SDK and that too worked , but when using the method from SDK (ActivateFactorAsync) it gives out the error as ( the endpoint does not support the provided HTTP method).

Then again i tried hitting the custom endpoint using SDK itself and its asking for stateToken required , even when i'm passing it.
Looking forward for some help  ,  Thank you.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9 ,
To help me with context in diagnosing the error that you're seeing, please submit a pull request with the minimum code required to  reproduce the issue.  I'm continuing investigation but this will be extremely helpful.  Thanks!

**Comment by amitSahu9** [comment]
> @amitSahu9 ,
> To help me with context in diagnosing the error that you're seeing, please submit a pull request with the minimum code required to reproduce the issue. I'm continuing investigation but this will be extremely helpful. Thanks!
@bryanapellanes-okta ,
I am preparing a new repository and with minimum required codes and will submit the request once that is done.
Will be waiting for your response.
Thank you for your help.

**Comment by amitSahu9** [comment]
@bryanapellanes-okta ,

        public async Task SendAsync(string phoneExtension , string phoneNumber)
        {
            var enrollOptions = new EnrollSmsFactorOptions()
            {
                StateToken = this.stateController.StateToken,
                PhoneExtension = phoneExtension,
                PhoneNumber = phoneNumber,
                FactorId = "mblry4uxieTrPiOcp0h7",
                Provider = this.Provider,
            };

            var authResponse = await this.authnClient.EnrollFactorAsync(enrollOptions);
            this.stateController.ProcessAuthnResponse(authResponse);
        }

While using this way, it says the user already has a verified phone number. So i tried this way :- 


        public async Task SendAsync(string phoneExtension, string phoneNumber)
        {
            var enrollOptions = new EnrollSmsFactorOptions()
            {
                StateToken = this.stateController.StateToken,
                PhoneExtension = phoneExtension,
                PhoneNumber = phoneNumber,
                FactorId = "mblry4uxieTrPiOcp0h7",
                Provider = this.Provider,
            };

            var request = new HttpRequest()
            {
                Uri = "/api/v1/authn/factors?updatePhone=true",
                Payload = enrollOptions,
            };

            var authResponse = await this.authnClient.PostAsync<AuthenticationResponse>(request);
            this.stateController.ProcessAuthnResponse(authResponse);
        }

so that it will update the phone number , but it says "The stateToken attribute is required in this context" , i printed the state token in logs to make sure it is being passed , but the issue persists. 

Hope this will help you understand the issue in a better way. 
Will be waiting for a response from you. Thank you

**Comment by amitSahu9** [comment]
Hello @bryanapellanes-okta  , is there any update on this issue , since i am relying on you for this issue . 

Looking forward for a response from you.

**Comment by bryanapellanes-okta** [comment]
> Hello @bryanapellanes-okta , is there any update on this issue , since i am relying on you for this issue .
> 
> Looking forward for a response from you.

I'm actively attempting to reproduce the issue you describe.  Preparing my environment and application state to match what I understand yours to be, but no definitive answer yet.  I appreciate your patience, I hope to have more information to share with you soon.

To help jump start my investigation, can you share a link to your code in a github repo that I can clone?

**Comment by bryanapellanes-okta** [comment]
@amitSahu9 Please see my previous comment.

**Comment by amitSahu9** [comment]
> @amitSahu9 Please see my previous comment.

@bryanapellanes-okta  thank you for the efforts that you are putting in. We dont have a repo in github currently , but since you asked i am working on it and as soon as it is done i will share the link so that you can clone.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9 Quick update, inquiring internally, I've been directed to this documentation: https://developer.okta.com/docs/reference/api/authn/#primary-authentication-with-public-application

I'm told that through the primary authentication process one can acquire a `stateToken` for use in the currently failing request.  I'm continuing investigation, but if you also review and explore, perhaps together we will arrive at a solution more quickly.

**Comment by amitSahu9** [comment]
@bryanapellanes-okta  Okay, that stateToken i'm already getting it when i am doing primary authentication . As this issue is coming at the time of enrollment , which happens to come after primary authentication . The issue is , even if i am passing the stateToken at the time of enrollment , it still says the state is required .  
The method in SDK i.e EnrollSmsFactorOptions should be able to take new number but it isnt taking. 
Even i am reviewing the code to see if i have missed something and exploring at the same time.  Thank you for cooperation.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9 ,
After further investigation internally, I've determined that the intent is to retire this library (Okta.Auth.Sdk) in favor of the Okta.Sdk (available on [github](https://github.com/okta/okta-sdk-dotnet) and on [nuget](https://www.nuget.org/packages/Okta.Sdk/)).

Functionality of this library (Okta.Auth.Sdk) is not well tested and not fully implemented in this scenario.  To enroll and activate an Sms factor you may use the [UserFactors.EnrollFactorAsync](https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk/Generated/UserFactorsClient.Generated.cs#L45) method provided in the Okta.Sdk (note the updatePhone parameter) additionally you may review code related to factor scenarios here: https://github.com/okta/okta-sdk-dotnet/blob/master/src/Okta.Sdk.IntegrationTests/FactorScenarios.cs.

I hope this helps, let me know if you need further information or assistance enabling your scenario.

**Comment by amitSahu9** [comment]
@bryanapellanes-okta  thank you so much for your efforts. Will follow the instructions as you mentioned. I hope everything will go fine that way. I will reach out to you if any further assistance in needed .

**Comment by amitSahu9** [comment]
hi @bryanapellanes-okta  , is it like the Okta.Auth.Sdk will be well implemented with regards to enrollment in future?
Just curious, since we are using that Sdk , it will be usefull if that is done. Please let me know if you have any information regarding this. 
Thanks..

**Comment by bryanapellanes-okta** [comment]
@amitSahu9 ,
Yes, it seems the intent is to properly implement and document Sms MFA enrollment and activation using the Okta.Auth.Sdk.  However, it is yet undetermined the amount of time this will take; hopefully using the Okta.Sdk for now will suit your needs while the Okta.Auth.Sdk is reviewed.

**Comment by amitSahu9** [comment]
@bryanapellanes-okta  , Well thanks a lot for informing. I would like to ask if you there is any way to use Okta.Sdk without using API token or Client ID , since we cannot use those in our project. Is there any possible approach for that , if yes please share it. 
Thanks.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
Unfortunately an API token is required to use Okta.Sdk.  I'll update here when there is more to share about using Okta.Auth.Sdk for your needs.  More to come, sorry for the inconvenience.

**Comment by amitSahu9** [comment]
Thank you so much @bryanapellanes-okta .
Do share more regarding this , your response will be highly awaited..

**Comment by laura-rodriguez** [comment]
Hi @amitSahu9 ,

Sorry for the inconvenience.

Can I ask you one more thing?

You mentioned it is working when using Postman, can you please share your Postman request? 
Also, can you post a Fiddler log with the request when using the SDK? 

I want to compare both so we can narrow the issue.

Thanks!

**Comment by amitSahu9** [comment]
@laura-rodriguez  
this is the request i am sending using postman for enrollment of sms with new number-
<img width="597" alt="enrollRequest" src="https://user-images.githubusercontent.com/54276202/90148524-06b1a500-dda1-11ea-9de6-eada8ad5dce6.PNG">

here is what i am using to activate the factor using postman - 
<img width="492" alt="smsActivate" src="https://user-images.githubusercontent.com/54276202/90148640-2cd74500-dda1-11ea-80af-940ddef00ae5.PNG">

the flow is  1-primary authentication  2-push verification 3-sms enrollment , this comes into picture when after the mfa is successful , the required factors should be enrolled to continue. I hope i was able to explain the scenario properly. Do let me know if this was of some help. 

I will be posting the fiddler response in a while, Thanks..

**Comment by amitSahu9** [comment]
@laura-rodriguez  here is the fiddler log, in text file.
[141_Full.txt](https://github.com/okta/okta-auth-dotnet/files/5074078/141_Full.txt)

this response corresponds to the following codes -

            public async Task SendAsync(string phoneExtension, string phoneNumber)
            {
            var enrollOptions = new EnrollSmsFactorOptions()
            {
                PhoneExtension = phoneExtension,
                PhoneNumber = phoneNumber,
                StateToken = this.stateController.StateToken,
                Provider = this.Provider,
                FactorId = "mblry4uxieTrPiOcp0h7",
            };
            var request = new HttpRequest()
            {
                Uri = "/api/v1/authn/factors",
                Payload = enrollOptions,
            };
            request.PathParameters = new Dictionary<string, object>()
            {
                ["updatePhone"] = true,
            };
            var authResponse = await this.authnClient.PostAsync<AuthenticationResponse>(request);
            this.stateController.ProcessAuthnResponse(authResponse);
        }

I got the error as "stateToken attribute is required int his context" . Do let me know if you have anything regarding this. Thanks.

**Comment by laura-rodriguez** [comment]
Hi @amitSahu9 ,

Thanks for the info.

It seems that the fiddler log you sent is incomplete. What I would like to see is the log when you send that request and the server response with the failure. Also, what the request you send looks like and headers. 

Can you please send us that info? Thanks!

**Comment by amitSahu9** [comment]
@laura-rodriguez  
Here are the files that you asked for- 
[13439_Full.txt](https://github.com/okta/okta-auth-dotnet/files/5075205/13439_Full.txt)
[13439_Request.txt](https://github.com/okta/okta-auth-dotnet/files/5075206/13439_Request.txt)
[13439_Response.txt](https://github.com/okta/okta-auth-dotnet/files/5075207/13439_Response.txt)

and this is request - 
  
    public async Task SendAsync(string phoneExtension, string phoneNumber)
        {
        var enrollOptions = new EnrollSmsFactorOptions()
        {
            PhoneExtension = phoneExtension,
            PhoneNumber = phoneNumber,
            StateToken = this.stateController.StateToken,
            Provider = this.Provider,
            FactorId = "mblry4uxieTrPiOcp0h7",
        };
        var request = new HttpRequest()
        {
            Uri = "/api/v1/authn/factors",
            Payload = enrollOptions,
        };
        request.PathParameters = new Dictionary<string, object>()
        {
            ["updatePhone"] = true,
        };
        var authResponse = await this.authnClient.PostAsync<AuthenticationResponse>(request);
        this.stateController.ProcessAuthnResponse(authResponse);

Do let me know if you need anything else regarding this . Thank you

**Comment by laura-rodriguez** [comment]
Thank you @amitSahu9 !

Doing a quick scan, the only diff between Postman and the SDK is the casing. In Postman you are using camel case vs pascal case in the SDK. I wonder if that could be the problem.

Have you tried passing the same JSON you are using on Postman as your payload when using the SDK? Something like this:

```
public async Task SendAsync(string phoneExtension, string phoneNumber)
    {
    var enrollOptions = new EnrollSmsFactorOptions()
    {
        PhoneExtension = phoneExtension,
        PhoneNumber = phoneNumber,
        StateToken = this.stateController.StateToken,
        Provider = this.Provider,
        FactorId = "mblry4uxieTrPiOcp0h7",
    };
    var request = new HttpRequest()
    {
        Uri = "/api/v1/authn/factors",
        Payload = @"{ stateToken:.., profile: { phoneNumber: ....} }",
    };
    request.PathParameters = new Dictionary<string, object>()
    {
        ["updatePhone"] = true,
    };
    var authResponse = await this.authnClient.PostAsync<AuthenticationResponse>(request);
    this.stateController.ProcessAuthnResponse(authResponse);
```

**Comment by amitSahu9** [comment]
@laura-rodriguez 
I was unaware of this casing , i will try the one which you have mentioned above and let you know,
Thank you for helping actively.

**Comment by amitSahu9** [comment]
@laura-rodriguez  
As you suggested to try pascal casing, i tried but got the response as "The request body was not well-formed." 
Here are the fiddler logs - 

[NewFull.txt](https://github.com/okta/okta-auth-dotnet/files/5083783/NewFull.txt)

And here is the code , do check the casing and let me know if any changes are needed :- 

      public async Task SendAsync(string phoneExtension, string phoneNumber)
        {
            var request = new HttpRequest()
            {
                Uri = "/api/v1/authn/factors?updatePhone=true",
                Payload = @"{ stateToken:" + this.stateController.StateToken + " ,factorType:sms, provider: OKTA,, profile: { phoneNumber:" + phoneNumber + "} }",
            };
            var authResponse = await this.authnClient.PostAsync<AuthenticationResponse>(request);
            this.stateController.ProcessAuthnResponse(authResponse);
        }

your response is awaited ,  thank you.

**Comment by laura-rodriguez** [comment]
Hi @amitSahu9 ,

Based on your Fiddler log it seems your payload was not constructed properly. This is what you sent:

```
Cookie: JSESSIONID=F83D0C5E8D21A09C3B915DFCFC4419E4; $Version=1; Okta_Verify_Autopush_-404356563=false; $Path=/
Content-Length: 121
Expect: 100-continue
Connection: Close

"{ stateToken: this.stateController.StateToken ,factorType:sms, provider: OKTA,, profile: { phoneNumber: phoneNumber } }"
```

Can you please try again with this piece of code? I'm using a dynamic object so you don't have to deal with the JSON format. 

```
public async Task SendAsync(string phoneExtension, string phoneNumber)
        {
            var authnClient = TestAuthenticationClient.Create();

            var payload = new
            {
                stateToken = this.stateController.StateToken,
                factorType = "sms",
                provider = "OKTA",
                profile = new
                {
                    phoneNumber = phoneNumber 
                },
            };
            var request = new Okta.Sdk.Abstractions.HttpRequest()
            {
                Uri = "/api/v1/authn/factors?updatePhone=true",
                Payload =  payload
            };
            var authResponse = await authnClient.PostAsync<AuthenticationResponse>(request);
            
        }
```

The payload you send should look like the one you send via Postman:

![image](https://user-images.githubusercontent.com/16751130/90444656-3e279680-e0ac-11ea-9553-9d152dd5a77b.png) 

I hope this helps.

**Comment by amitSahu9** [comment]
@laura-rodriguez  
The above mentioned code actually worked properly , but the problem now is activation. 
I tried to keep it exactly same as postman, still error occured. Trying different scenarios. 
  
     public async Task VerifyAsync(string passCode)
        {
            var payload = new 
            {
                stateToken = this.stateController.StateToken,
                PassCode = passCode,
            };
            var request = new HttpRequest()
            {
                Uri = "/api/v1/authn/factors/mblry4uxieTrPiOcp0h7/lifecycle/activate",
                Payload = payload,
            };
            var authResponse = await this.authnClient.PostAsync<AuthenticationResponse>(request);
            this.stateController.ProcessAuthnResponse(authResponse);
        }

this also i tried but didnt actually work, let me know if you have something regarding this . Thanks a lot.

**Comment by laura-rodriguez** [comment]
@amitSahu9 is [this](https://developer.okta.com/docs/reference/api/authn/#activate-sms-factor-request-example) the request you are trying to do?

Can you please post again the activation working on Postman and the Fiddler log when using the SDK?

**Comment by amitSahu9** [comment]
@laura-rodriguez  yes that is the one.
When trying to activate using sdk , again facing issue.
Here are the fiddler logs for request as well as response :-
[1012_Request.txt](https://github.com/okta/okta-auth-dotnet/files/5091284/1012_Request.txt)
[1012_Response.txt](https://github.com/okta/okta-auth-dotnet/files/5091286/1012_Response.txt)

And here is the code which i used  :- 

      public async Task VerifyAsync(string passCode)
        {
            var activateOptions = new ActivateFactorOptions()
            {
                FactorId = "mbltfp0p9gacMRGqC0h7",
                PassCode = passCode,
                StateToken = this.stateController.StateToken,
            };

            var authResponse = await this.authnClient.ActivateFactorAsync(activateOptions);
            this.stateController.ProcessAuthnResponse(authResponse);
        }
I am also trying to do in other ways , let me know if you have something, Thank you..

**Comment by laura-rodriguez** [comment]
Hmm the request looks good to me. It seems the API doesn't find a factor with id = `mbltfp0p9gacMRGqC0h7`.  Can you double check if the factor id is correct?

Sorry if I keep asking this, but does the same request with same factor id work in Postman? because you should have the same response.

**Comment by amitSahu9** [comment]
@laura-rodriguez ,
Yes as you said , nothing was wrong and it is working now properly.
I still have to test it a few more times. Thank you for helping actively ..

**Comment by amitSahu9** [comment]
@laura-rodriguez  
sorry for the trouble again, it seems this way of activation is working sometimes, and sometimes throwing error as "errorSummary=Not found: Resource not found: mbltfp0p9gacMRGqC0h7 (UserFactor)" , dont know where is the issue, still trying to figure out.
Let me know if you have any suggestions. Thank you.

**Comment by laura-rodriguez** [comment]
@amitSahu9 It seems that endpoint needs some time after enrollment to replicate the factor in the DB. Sometimes, this behavior is expected. I suggest you take a look at the [API Reference](https://developer.okta.com/docs/reference/api/authn). 
You could potentially implement a retry logic until the factor is found.

**Comment by amitSahu9** [comment]
@laura-rodriguez  , I think i have identified the issue, it is related to the factorId as you mentioned before . 
Need to check that.

**Comment by amitSahu9** [comment]
@laura-rodriguez  @bryanapellanes-okta  
Thank you for your help, all the issues that i had related to the SDK has been resolved. Thank you for active help;

**Comment by laura-rodriguez** [comment]
We do have a unit test that verifies that [`EnrollFactorAsync` sends a correct JSON](https://github.com/okta/okta-auth-dotnet/blob/master/Okta.Auth.Sdk.UnitTests/AuthenticationClientShould.cs#L471) , so anyone should be able to use that method instead of doing the request manually.
