### ISSUE TITLE
Is there any method included in the SDK to  verify the authenticity of the response getting from Okta

### ISSUE THREAD

**Issue by amitSahu9** [okta/okta-auth-dotnet#38]
After getting response from Okta i want to authenticate the response so that i can reduce the chances of phishing such as man in the middle attack . Just want to know if there is a way to check using the SDK that the response recieved is from Okta , i.e, is Authentic.
Looking forward to hearing back , Thank you.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9 ,
Thank you for your question.

There is no api call that you can use specifically for this purpose.  All calls made to the Okta api use HTTPS; there are mechanisms one may use to validate the authenticity of the SSL certificate (in fact this will often happen automatically depending on your platftorm).  However, this is outside the scope of our Sdk.

Feel free to reach out if you have other questions.  Thanks!
