### ISSUE TITLE
Force MFA_REQUIRED and clear DeviceTokens

### ISSUE THREAD

**Issue by gituser22kk** [okta/okta-auth-dotnet#46]
Hello,

(A) We use .Net 2.2 with Auth SDK version v1.1.0.  and authenticate users through apis (they don't login to Okta's tenant). The user is authenticated using DeviceToken and DeviceFingerprint. Later, if the user goes through recovery process they correctly go through MFA_REQUIRED step. However, if the user authenticates again (instead of completing the MFA_REQUIRED process) they don't go through MFA challenge, since the DeviceToken is already registered. Is there any way to force MFA challenge after recovery process is completed?

(B) Is there any method to clear DeviceTokens and DeviceFingerPrint for a user? We want the users to go through MFA Challenge after the user completes recovery process.

Thank you!

**Comment by bryanapellanes-okta** [comment]
@gituser22kk,
Thanks for getting in touch.

(A) To require MFA You may have luck following the instructions here: [https://developer.okta.com/docs/guides/configure-signon-policy/-/prompt-factor-group/](https://developer.okta.com/docs/guides/configure-signon-policy/-/prompt-factor-group/)

(B) We don't appear to have a documented way to clear device tokens or finger prints via api call.  I will inquire internally and respond here when I have more information to share.

**Comment by gituser22kk** [comment]
> 
> 
> @gituser22kk,
> Thanks for getting in touch.
> 
> (A) To require MFA You may have luck following the instructions here: https://developer.okta.com/docs/guides/configure-signon-policy/-/prompt-factor-group/
> 
> (B) We don't appear to have a documented way to clear device tokens or finger prints via api call. I will inquire internally and respond here when I have more information to share.

Thanks for replying. We do have sign-on policy setup to prompt for MFA (per device). However, if the user goes through recovery we want to prompt for MFA challenge again (regardless if the DeviceToken is already registered). The "state machine" shows MFA_REQUIRED after recovery but looks like it skips that if the DeviceToken is already set. Thank you!

**Comment by bryanapellanes-okta** [comment]
@gituser22kk,
Internal inquiry reveals that the functionality you're looking for does not exist in the product.  Additional information can be found at this link shared with me by a developer responsible for that area: [https://developer.okta.com/docs/reference/api/authn/#device-fingerprint-best-practices](https://developer.okta.com/docs/reference/api/authn/#device-fingerprint-best-practices).  

Sorry for the inconvenience.  Thanks for using Okta!
