### ISSUE TITLE
Can’t get statetoken (always null)

### ISSUE THREAD

**Issue by guilherme-difranco** [okta/okta-auth-dotnet#47]
I’m trying to implement change password method and I need to set statetoken, but it always comes null when the user logs in ![okta](https://user-images.githubusercontent.com/57638011/96141607-8eb64700-0ed7-11eb-9225-0fc436511c4b.png)

I took this example used for testing (https://github.com/okta/okta-auth-dotnet/blob/8611e10f37c9da5350e3e0ed10d0b68a76717a58/Okta.Auth.Sdk.IntegrationTests/AuthenticationScenarios.cs), where statetoken could not be empty, but it is not what happens…

**Comment by bryanapellanes-okta** [comment]
@guilherme-difranco,
Thank you for your question, and I apologize for the inconvenience.  I have a couple questions to help me get a better understanding of what is happening:

1) If you make the same request via postman, do you get the state token?
2) Does the `authnResponse` contain the state token in it's `_data` field?  You can get this by calling `authnResponse.GetStringProperty("stateToken")`.

**Comment by guilherme-difranco** [comment]
Hi @bryanapellanes-okta,

thank you in advance for your help, answering your questions:

1- No, statetoken is not shown in json return 
![image](https://user-images.githubusercontent.com/57638011/96173480-4fe7b780-0efe-11eb-9c13-a043f15aec1e.png)

2-  It does not contain statetoken too
![image](https://user-images.githubusercontent.com/57638011/96174363-9689e180-0eff-11eb-9ba1-b30889cc9ddd.png)

**Comment by bryanapellanes-okta** [comment]
@guilherme-difranco,
I apologize for the delay; I've inquired internally with no definitive answer yet found.  Would you be able to provide sample code that reproduces this issue in a temporary github repository?  I can then review more closely to hopefully determine the cause of the issue.

**Comment by guilherme-difranco** [comment]
@bryanapellanes-okta 

`  var oktaClient = new OktaClient( new OktaClientConfiguration { OktaDomain = _okta.Base_url, Token = _okta.Token });
            var guid = Guid.NewGuid();

            var createdUser = await oktaClient.Users.CreateUserAsync(new CreateUserWithPasswordOptions
            {
                Profile = new UserProfile
                {
                    FirstName = "John",
                    LastName = "Test",
                    Email = $"john-expired-pass-dotnet-authn-{guid}@example.com",
                    Login = $"john-expired-pass-dotnet-authn-{guid}@example.com",
                },
                Password = "Okta1234!",
                Activate = true,
            });


            try
            {
                await createdUser.ExpirePasswordAsync();              

                var authnOptions = new AuthenticateOptions()
                {
                    Username = $"john-expired-pass-dotnet-authn-{guid}@example.com",
                    Password = "Okta1234!",
                    MultiOptionalFactorEnroll = true,
                    WarnBeforePasswordExpired = true,
                };

                var authnResponse = await clientOKTA().AuthenticateAsync(authnOptions);

                //authnResponse.Should().NotBeNull();
                //authnResponse.StateToken.Should().NotBeNullOrEmpty();
                //authnResponse.AuthenticationStatus.Should().Be(AuthenticationStatus.PasswordExpired);
                //authnResponse.Links.Should().NotBeNull();
            }
            finally
            {
                await createdUser.DeactivateAsync();
                await createdUser.DeactivateOrDeleteAsync();
            }`

**Comment by bryanapellanes-okta** [comment]
@guilherme-difranco,
I've received additional information from our internal developers familiar with this area.   Excerpt from their response follows:


> The absence of the `stateToken` is correct (intended behaviour) — the `stateToken` has fulfilled its role of stepping through the authentication process and reaching the SUCCESS state, so now the `sessionToken` has been issued and the `stateToken` has been put out to pasture.

Hope this helps!  Thanks!

**Comment by guilherme-difranco** [comment]
@bryanapellanes-okta 
thank you for all your help, 
my problem is that i can't get statetoken to reset the password with trusted application,
so how to obtain statetoken for this password reset? I've tried to set it but I can't get it to work at all ...
do you have any example i can follow?

**Comment by bryanapellanes-okta** [comment]
@guilherme-difranco,
Can you give me more information about your use case?  Are you building an interaction that allows a user to reset their own password, or, are you trying to enable an administrator to reset a user's password?  The guidance I provide would be based on your application scenario.  Thanks!

**Comment by guilherme-difranco** [comment]
Hi @bryanapellanes-okta 

after all your help, activating the account and registering a question for recovery I managed to reset the password, thanks!

**Comment by bryanapellanes-okta** [comment]
@guilherme-difranco,
Awesome! Glad to hear it!  Thanks for using Okta!
