### ISSUE TITLE
No support for Okta totp enrollment  through SDK

### ISSUE THREAD

**Issue by amitSahu9** [okta/okta-auth-dotnet#48]
Hello, this is regarding Okta TOTP enrollment through the SDK, i checked throughly and there is no method present for totp enrollment through this SDK , just wanted to know if this is going to be added in this SDK or not,  thank you.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
Thanks for reaching out!  Have you tried using this method: [https://github.com/okta/okta-auth-dotnet/blob/master/Okta.Auth.Sdk/AuthenticationClient.cs#L387](https://github.com/okta/okta-auth-dotnet/blob/master/Okta.Auth.Sdk/AuthenticationClient.cs#L387)?

**Comment by amitSahu9** [comment]
> @amitSahu9,
> Thanks for reaching out! Have you tried using this method: https://github.com/okta/okta-auth-dotnet/blob/master/Okta.Auth.Sdk/AuthenticationClient.cs#L387?

Yes i am calling the API that way, just wanted to know if it is supported by the SDK. Thanks @bryanapellanes-okta

**Comment by amitSahu9** [comment]
@bryanapellanes-okta actually i was asking regarding Enrolling in Okta Verify using the Email or Sms , which usually appears after we cant scan the QR code. ?

**Comment by bryanapellanes-okta** [comment]
> @bryanapellanes-okta actually i was asking regarding Enrolling in Okta Verify using the Email or Sms , which usually appears after we cant scan the QR code. ?

You can enroll in Okta Verify using `EnrollPushFactorOptions`, see [https://github.com/okta/okta-auth-dotnet#enroll-okta-verify-push-factor](https://github.com/okta/okta-auth-dotnet#enroll-okta-verify-push-factor).
