### ISSUE TITLE
How to integrate Duo Factor using Okta.Auth.Sdk

### ISSUE THREAD

**Issue by amitSahu9** [okta/okta-auth-dotnet#59]
How to add support for Duo Factor using Okta.Auth.Sdk . While hitting the Authentication method for DUO using the SDK we are not getting the push on Duo Security application .

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
Thanks for reaching out!  To help me understand your use case better, can you share sample code that reproduces the issue?

**Comment by amitSahu9** [comment]
hi @bryanapellanes-okta  , i have tried hitting the api using the SDK -

public async Task SendAsync()
        {
            var verifyDuoFactorOptions = new VerifyDuoFactorOptions()
            {
                FactorId = this.Id,
                StateToken = this.stateController.StateToken,
            };
            var authResponse = await this.authnClient.VerifyFactorAsync(verifyDuoFactorOptions);
        }

but i am not getting the push on Duo security app.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
Thanks for providing the additional information.  I'll review more closely and reply here when I have more to share.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
After inquiring further internally, our Sdk engineers are not familiar with this factor so I will need to inquire deeper in the organization.  To help direct my investigation, please provide the raw request/response data from your test; this will help me find the appropriate group to go to.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
This link provides additional information on Duo factor enrollment and details the steps necessary:
- https://developer.okta.com/docs/reference/api/authn/?_ga=2.62669612.1266625241.1614027787-466632308.1587499635#enroll-duo-factor

**Comment by amitSahu9** [comment]
Hey @bryanapellanes-okta  

var verifyFactorOptions = new VerifyDuoFactorOptions()
{
    FactorId = "ostf1fmaMGJLMNGNLIVG",
    StateToken = "foo",
};

var authResponse = await authnClient.VerifyFactorAsync(verifyFactorOptions);

is this the correct way for DUO authentication using this SDK? can you please verify if its working?

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
I've opened an internal item so additional focus may be applied to providing you an answer.

**Comment by amitSahu9** [comment]
> @amitSahu9,
> I've opened an internal item so additional focus may be applied to providing you an answer.

after making the API call i am getting a proper response , which shows the status as MFA_CHALLENGE,, and factorResult is WAITING, but i am not getting the push on DUO app, is any step missing or atleast let me know if i am doing anything wrong,

**Comment by bryanapellanes-okta** [comment]
> after making the API call i am getting a proper response , which shows the status as MFA_CHALLENGE,, and factorResult is WAITING, but i am not getting the push on DUO app, is any step missing or atleast let me know if i am doing anything wrong,

Based on your description I don't believe you are doing anything wrong.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
Additional documentation on Duo is also available here: https://duo.com/docs/duoweb

**Comment by amitSahu9** [comment]
@bryanapellanes-okta  could you replicate the same? is it working for you?

**Comment by bryanapellanes-okta** [comment]
> @bryanapellanes-okta could you replicate the same? is it working for you?

I've opened an internal item so additional focus may be applied to providing you an answer.  I'll inquire internally to provide you a response.

**Comment by amitSahu9** [comment]
> > @bryanapellanes-okta could you replicate the same? is it working for you?
> 
> I've opened an internal item so additional focus may be applied to providing you an answer. I'll inquire internally to provide you a response.

hi @bryanapellanes-okta , any update regarding the issue.. Thank you..

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
Sorry for the delay, no update yet.  I'm working simultaneously to understand the Duo factor myself as well as inquiring internally to find the team responsible for that area so they may provide additional assistance.

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
While I try to find additional assistance internally, have you had a chance to review the documentation [Verify Duo Factor](https://developer.okta.com/docs/reference/api/authn/?_ga=2.62669612.1266625241.1614027787-466632308.1587499635#verify-duo-factor)?  

Based on this I think you need to perform a primary authentication, see [Primary Authentication](https://developer.okta.com/docs/reference/api/authn/#primary-authentication) and provide the stateToken to [Verify Duo Factor](https://developer.okta.com/docs/reference/api/authn/?_ga=2.62669612.1266625241.1614027787-466632308.1587499635#verify-duo-factor).  Your code is using the value `foo` which will not work.

**Comment by amitSahu9** [comment]
> @amitSahu9,
> While I try to find additional assistance internally, have you had a chance to review the documentation [Verify Duo Factor](https://developer.okta.com/docs/reference/api/authn/?_ga=2.62669612.1266625241.1614027787-466632308.1587499635#verify-duo-factor)?
> 
> Based on this I think you need to perform a primary authentication, see [Primary Authentication](https://developer.okta.com/docs/reference/api/authn/#primary-authentication) (see also, https://devforum.okta.com/t/how-to-get-statetoken/11896/4) and provide the stateToken to [Verify Duo Factor](https://developer.okta.com/docs/reference/api/authn/?_ga=2.62669612.1266625241.1614027787-466632308.1587499635#verify-duo-factor). Your code is using the value `foo` which will not work.

@bryanapellanes-okta   , 
I am doing it the correct way, with primary authentication, and i'm also getting the response . That piece of code i just copied from the documentation of this SDk, I am also getting proper response but not getting the push on Duo app..

**Comment by amitSahu9** [comment]
> @amitSahu9,
> While I try to find additional assistance internally, have you had a chance to review the documentation [Verify Duo Factor](https://developer.okta.com/docs/reference/api/authn/?_ga=2.62669612.1266625241.1614027787-466632308.1587499635#verify-duo-factor)?
> 
> Based on this I think you need to perform a primary authentication, see [Primary Authentication](https://developer.okta.com/docs/reference/api/authn/#primary-authentication) (see also, https://devforum.okta.com/t/how-to-get-statetoken/11896/4) and provide the stateToken to [Verify Duo Factor](https://developer.okta.com/docs/reference/api/authn/?_ga=2.62669612.1266625241.1614027787-466632308.1587499635#verify-duo-factor). Your code is using the value `foo` which will not work.


     var verifyFactorOptions = new VerifyDuoFactorOptions()
            {
                FactorId = this.Id,
                StateToken = this.stateController.StateToken,
            };

            var authResponse = await authnClient.VerifyFactorAsync(verifyFactorOptions);

 this is what i am doing.. @bryanapellanes-okta

**Comment by bryanapellanes-okta** [comment]
@amitSahu9,
Acknowledged, I will need to investigate further since I don't know why it isn't working.  This work will be prioritized against other work; I hope to have an answer after having a chance to experiment with the Duo and other push factors.

**Comment by amitSahu9** [comment]
> @amitSahu9,
> Acknowledged, I will need to investigate further since I don't know why it isn't working. This work will be prioritized against other work; I hope to have an answer after having a chance to experiment with the Duo and other push factors.

@bryanapellanes-okta  Thank you , and i think after the Api call is made to Okta for Duo authentication, 

    var authResponse = await authnClient.VerifyFactorAsync(verifyFactorOptions);

after this there are some more api calls to communicate with DUO server. Maybe that is missing.

**Comment by amitSahu9** [comment]
hi @bryanapellanes-okta any update on this?

**Comment by bryanapellanes-okta** [comment]
> hi @bryanapellanes-okta any update on this?

@amitSahu9 
After further review this appears to be an issue with the API.  I think it might be a good idea for you to contact our developer support team at developers@okta.com so we can have a deeper conversation, and help resolve your problem quicker.  I've let them know about this issue and to expect someone to reach out.

**Comment by andriizhegurov-okta** [comment]
@amitSahu9 
This is an expected behavior. 
DUO is a web factor and after `VerifyFactorAsync` is called, Duo widget has to be presented to user. The widget lets the user choose a Push or SMS verification, and it starts actual Duo authentication.
Please see [Authentication API | Verify Duo Factor](https://developer.okta.com/docs/reference/api/authn/#verify-duo-factor) for more details.

**Comment by andriizhegurov-okta** [comment]
Closing the issue because it's an expected behavior. Feel free to reopen if you need additional assistance.
