### ISSUE TITLE
Add Authorization code flow support

### ISSUE THREAD

**Issue by oliverjanik** [okta/okta-auth-dotnet#67]
Given I have ClientId, ClientSecret, Domain, and authorization code (after redirecting to Okta sign-in page)

How do verify the authorization code received ? I believe it's the /token endpoint.

Seems like the only supported flow in this package is username/password?

**Comment by andriizhegurov-okta** [comment]
Hi @oliverjanik. I'll inquire internally if the flow is supported by the package and update you here.
Can you also give us more details about your use case? This will help us to understand your scenario better. Thanks.

**Comment by andriizhegurov-okta** [comment]
@oliverjanik Okta.Auth.Sdk only supports username/password flow. 
If you're using Okta sign-in widget in Asp.Net/Asp.Net Core application, you may want to employ [Okta.AspNet](/okta/okta-aspnet) instead. If this is not your case, you will unfortunately need to implement the flow manually.

**Comment by oliverjanik** [comment]
I have found the Okta.AspNet packages however they are too tightly coupled to the fat framework and generally carry a lot of assumptions.

All I need is a simple lean call `Authenticate(domain, clientId, clientSecret, code` that returns the access token and refresh token.

And another one that calls /userinfo endpoint to fetch information about logged in user.

**Comment by laura-rodriguez** [comment]
The Auth SDK is not intended to cover OIDC but the Okta Authn API. For OIDC, you can use the Asp.NET SDK or [make the calls to the API](https://developer.okta.com/docs/reference/api/oidc/).
