### ISSUE TITLE
Support for V4.0+

### ISSUE THREAD

**Issue by Saichethan** [okta/okta-auth-dotnet#82]
### Describe the feature request?

Hello, I am trying to use Okta.Auth.SDK for our legacy system written in .NET Framework (V4.0.3+). Is there a way for me to use this without migrating our codebase?

### New or Affected Resource(s)

N/A

**Comment by laura-rodriguez** [comment]
Hi @Saichethan,

Unfortunately, this SDK is not compatible with .NET framework < 4.5.  The options you have is to fork this project and make the necessary changes to be compatible with your legacy system or use the [API](https://developer.okta.com/docs/reference/api/authn/).

I hope this helps.
